INSERT INTO maker(id, name) VALUES(1, 'Asus');
INSERT INTO maker(id, name) VALUES(2, 'Lenovo');
INSERT INTO maker(id, name) VALUES(3, 'Hewlett-Packard');
INSERT INTO maker(id, name) VALUES(4, 'Samsung');
INSERT INTO maker(id, name) VALUES(5, 'Seagate');
INSERT INTO maker(id, name) VALUES(6, 'Crucial');
INSERT INTO maker(id, name) VALUES(7, 'Gigabyte');
INSERT INTO maker(id, name) VALUES(8, 'Huawei');
INSERT INTO maker(id, name) VALUES(9, 'Xiaomi');

INSERT INTO product(id, name, price, maker_id) VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO product(id, name, price, maker_id) VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO product(id, name, price, maker_id) VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO product(id, name, price, maker_id) VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO product(id, name, price, maker_id) VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO product(id, name, price, maker_id) VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO product(id, name, price, maker_id) VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO product(id, name, price, maker_id) VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO product(id, name, price, maker_id) VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO product(id, name, price, maker_id) VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO product(id, name, price, maker_id) VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);